# src/api/api_v1/pipeline/facebook/config.py
from facebook_business.adobjects.adaccount import AdAccount
from facebook_business.adobjects.campaign import Campaign
from facebook_business.adobjects.adset import AdSet
from facebook_business.adobjects.ad import Ad
from facebook_business.adobjects.adcreative import AdCreative

from facebook_business.adobjects.adsinsights import AdsInsights

ACCOUNT_FIELDS = [
    AdAccount.Field.account_id,
    AdAccount.Field.name,
    AdAccount.Field.account_status,
    AdAccount.Field.owner,
    AdAccount.Field.amount_spent,
    AdAccount.Field.balance,
    AdAccount.Field.currency,
    AdAccount.Field.created_time,
    AdAccount.Field.age,
    AdAccount.Field.spend_cap,
    AdAccount.Field.capabilities,
]


CAMPAIGN_FIELDS = [
    Campaign.Field.id,
    Campaign.Field.account_id,
    Campaign.Field.name,
    Campaign.Field.source_campaign_id,
    Campaign.Field.bid_strategy,
    Campaign.Field.boosted_object_id,
    Campaign.Field.budget_rebalance_flag,
    Campaign.Field.budget_remaining,
    Campaign.Field.buying_type,
    Campaign.Field.can_create_brand_lift_study,
    Campaign.Field.can_use_spend_cap,
    Campaign.Field.configured_status,
    Campaign.Field.created_time,
    Campaign.Field.daily_budget,
    Campaign.Field.effective_status,
    Campaign.Field.is_skadnetwork_attribution,
    Campaign.Field.last_budget_toggling_time,
    Campaign.Field.lifetime_budget,
    Campaign.Field.objective,
    Campaign.Field.smart_promotion_type,
    Campaign.Field.special_ad_category,
    Campaign.Field.spend_cap,
    Campaign.Field.start_time,
    Campaign.Field.status,
    Campaign.Field.stop_time,
    Campaign.Field.topline_id,
    Campaign.Field.pacing_type,
    Campaign.Field.special_ad_categories,
    Campaign.Field.special_ad_category_country,
    Campaign.Field.promoted_object,
    Campaign.Field.updated_time,
]

ADSET_FIELDS = [
    AdSet.Field.id,
    AdSet.Field.account_id,
    AdSet.Field.campaign_id,
    AdSet.Field.name,
    AdSet.Field.source_adset_id,
    AdSet.Field.asset_feed_id,
    AdSet.Field.bid_amount,
    # AdSet.Field.bid_info,
    AdSet.Field.bid_strategy,
    AdSet.Field.billing_event,
    AdSet.Field.budget_remaining,
    AdSet.Field.configured_status,
    AdSet.Field.created_time,
    AdSet.Field.daily_budget,
    AdSet.Field.daily_min_spend_target,
    AdSet.Field.daily_spend_cap,
    AdSet.Field.destination_type,
    AdSet.Field.effective_status,
    AdSet.Field.start_time,
    AdSet.Field.end_time,
    AdSet.Field.is_dynamic_creative,
    # AdSet.Field.learning_stage_info,
    AdSet.Field.lifetime_budget,
    AdSet.Field.lifetime_imps,
    AdSet.Field.lifetime_min_spend_target,
    AdSet.Field.lifetime_spend_cap,
    AdSet.Field.multi_optimization_goal_weight,
    AdSet.Field.optimization_goal,
    AdSet.Field.optimization_sub_event,
    # AdSet.Field.promoted_object,
    AdSet.Field.recurring_budget_semantics,
    AdSet.Field.rf_prediction_id,
    AdSet.Field.review_feedback,
    AdSet.Field.status,
    AdSet.Field.use_new_app_click,
    AdSet.Field.targeting,
    AdSet.Field.attribution_spec,
    AdSet.Field.updated_time,
]

AD_FIELDS = [
    Ad.Field.id,
    Ad.Field.account_id,
    Ad.Field.campaign_id,
    Ad.Field.adset_id,
    Ad.Field.name,
    Ad.Field.creative,
    Ad.Field.bid_amount,
    Ad.Field.bid_type,
    Ad.Field.configured_status,
    Ad.Field.conversion_domain,
    Ad.Field.created_time,
    Ad.Field.effective_status,
    Ad.Field.last_updated_by_app_id,
    Ad.Field.preview_shareable_link,
    Ad.Field.status,
    Ad.Field.source_ad_id,
    Ad.Field.updated_time,
]

CREATIVE_FIELDS = [
    AdCreative.Field.id,
    AdCreative.Field.account_id,
    AdCreative.Field.name,
    AdCreative.Field.actor_id,
    AdCreative.Field.applink_treatment,
    AdCreative.Field.authorization_category,
    AdCreative.Field.body,
    AdCreative.Field.branded_content_sponsor_page_id,
    AdCreative.Field.bundle_folder_id,
    AdCreative.Field.call_to_action_type,
    AdCreative.Field.categorization_criteria,
    AdCreative.Field.category_media_source,
    AdCreative.Field.destination_set_id,
    AdCreative.Field.dynamic_ad_voice,
    AdCreative.Field.effective_authorization_category,
    AdCreative.Field.effective_instagram_media_id,
    AdCreative.Field.effective_object_story_id,
    AdCreative.Field.enable_direct_install,
    AdCreative.Field.image_hash,
    AdCreative.Field.image_url,
    AdCreative.Field.instagram_permalink_url,
    AdCreative.Field.link_destination_display_url,
    AdCreative.Field.link_og_id,
    AdCreative.Field.link_url,
    AdCreative.Field.object_id,
    AdCreative.Field.place_page_set_id,
    AdCreative.Field.playable_asset_id,
    AdCreative.Field.product_set_id,
    AdCreative.Field.source_instagram_media_id,
    AdCreative.Field.status,
    AdCreative.Field.thumbnail_id,
    AdCreative.Field.thumbnail_url,
    AdCreative.Field.title,
    AdCreative.Field.use_page_actor_override,
    AdCreative.Field.video_id,
    AdCreative.Field.url_tags,
    AdCreative.Field.object_story_spec,
    AdCreative.Field.platform_customizations,
    AdCreative.Field.template_url,
    AdCreative.Field.template_url_spec,
]

INSIGHTS_FIELDS = [
    AdsInsights.Field.date_start,
    AdsInsights.Field.date_stop,
    AdsInsights.Field.account_id,
    AdsInsights.Field.account_name,
    AdsInsights.Field.account_currency,
    AdsInsights.Field.campaign_id,
    AdsInsights.Field.campaign_name,
    AdsInsights.Field.buying_type,
    AdsInsights.Field.objective,
    AdsInsights.Field.adset_id,
    AdsInsights.Field.adset_name,
    AdsInsights.Field.ad_id,
    AdsInsights.Field.ad_name,
    AdsInsights.Field.created_time,
    AdsInsights.Field.clicks,
    AdsInsights.Field.impressions,
    AdsInsights.Field.reach,
    AdsInsights.Field.spend,
    AdsInsights.Field.actions,
    AdsInsights.Field.conversions,
    AdsInsights.Field.inline_link_clicks,
    AdsInsights.Field.inline_link_click_ctr,
    AdsInsights.Field.inline_post_engagement,
    AdsInsights.Field.social_spend,
    AdsInsights.Field.unique_clicks,
    AdsInsights.Field.unique_ctr,
    AdsInsights.Field.unique_inline_link_clicks,
    AdsInsights.Field.unique_inline_link_click_ctr,
    AdsInsights.Field.unique_link_clicks_ctr,
    AdsInsights.Field.quality_ranking,
    AdsInsights.Field.engagement_rate_ranking,
    AdsInsights.Field.conversion_rate_ranking,
    AdsInsights.Field.video_thruplay_watched_actions,
]

DEFAULT_PARAMS = {
    "level": "ad",
    "breakdowns": ["platform_position", "publisher_platform"],
    "time_increment": 1,
}
